SELECT * FROM got.casas;
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (2,'Allyrion of Godsgrace','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (3,'Amber','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (4,'Ambrose','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (5,'Andrik of Southshield','Iron Islands (Shield Islands)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (6,'Appleton of Appleton','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (7,'Arryn of Gulltown','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (8,'Arryn of the Eyrie','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (9,'Ashford of Ashford','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (10,'Ashwood','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (11,'Baelish of Harrenhal','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (12,'Baelish of the Fingers','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (13,'Ball','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (14,'Banefort of Banefort','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (15,'Bar Emmon of Sharp Point','Crownlands (Dragonstone)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (16,'Baratheon of Dragonstone','Crownlands (Dragonstone)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (17,'Baratheon of King''s Landing','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (18,'Baratheon of Storm''s End','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (19,'Beesbury of Honeyholt','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (20,'Belgrave','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (21,'Belmore of Strongsong','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (22,'Bettley','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (23,'Bigglestone','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (24,'Blackbar of Bandallon','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (25,'Blackberry','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (26,'Blackfyre','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (27,'Blackmont of Blackmont','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (28,'Blackmyre','North (Crannogmen)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (29,'Blacktyde of Blacktyde','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (30,'Blackwood of Raventree Hall','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (31,'Blanetree','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (32,'Blount','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (33,'Boggs','Crownlands (Crackclaw Point)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (34,'Boggs','North (Crannogmen)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (35,'Bole','North (Wolfswood Clans)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (36,'Bolling','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (37,'Bolton of the Dreadfort','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (38,'Bolton of Winterfell','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (39,'Borrell of Sweetsister','Vale of Arryn (Sistermen)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (40,'Botley of Lordsport','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (41,'Bracken of Stone Hedge','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (42,'Branch','North (Wolfswood Clans)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (43,'Brax of Hornvale','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (44,'Breakstone','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (45,'Briar','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (46,'Bridges','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (47,'Brightstone','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (48,'Brook','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (49,'Broom','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (50,'Brownhill','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (51,'Brune of Brownhollow','Crownlands (Crackclaw Point)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (52,'Brune of the Dyre Den','Crownlands (Crackclaw Point)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (53,'Buckler of Bronzegate','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (54,'Buckwell of the Antlers','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (55,'Bulwer of Blackcrown','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (56,'Burley','North (Mountain Clans)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (57,'Bushy','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (58,'Butterwell of Whitewalls','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (59,'Byrch','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (60,'Bywater','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (61,'Cafferen of Fawnton','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (62,'Cargyll','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (63,'Caron of Nightsong','Stormlands (Marcher Lords)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (64,'Cassel','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (65,'Casterly of Casterly Rock','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (66,'Caswell of Bitterbridge','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (67,'Cave','Crownlands (Crackclaw Point)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (68,'Celtigar of Claw Isle','Crownlands (Dragonstone)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (69,'Cerwyn of Castle Cerwyn','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (70,'Chambers','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (71,'Charlton','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (72,'Chelsted','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (73,'Chester of Greenshield','Reach (Shield Islands)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (74,'Chyttering','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (75,'Clegane of Clegane''s Keep','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (76,'Clifton','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (77,'Cobb','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (78,'Cockshaw','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (79,'Codd','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (80,'Coldwater of Coldwater Burn','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (81,'Cole','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (82,'Condon','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (83,'Conklyn','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (84,'Connington of Griffin''s Roost','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (85,'Corbray of Heart''s Home','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (86,'Cordwayner of Hammerhal','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (87,'Costayne of the Three Towers','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (88,'Cox of Saltpans','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (89,'Crabb of the Whispers','Crownlands (Crackclaw Point)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (90,'Crakehall of Crakehall','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (91,'Crane of Red Lake','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (92,'Cray','North (Crannogmen)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (93,'Cressey','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (94,'Crowl of Deepdown','North (Skagosi Clans)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (95,'Cupps','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (96,'Cuy of Sunhouse','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (97,'Dalt of Lemonwood','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (98,'Dargood','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (99,'Darke','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (100,'Darklyn of Duskendale','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (101,'Darkwood','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (102,'Darry of Darry','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (103,'Dayne of High Hermitage','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (104,'Dayne of Starfall','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (105,'Deddings','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (106,'Doggett','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (107,'Dondarrion of Blackhaven','Stormlands (Marcher Lords)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (108,'Donniger','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (109,'Drinkwater','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (110,'Drox','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (111,'Drumm of Old Wyk','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (112,'Dryland of Hellgate Hall','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (113,'Dunn','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (114,'Durrandon','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (115,'Durwell','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (116,'Dustin of Barrowton','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (117,'Edgerton','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (118,'Egen','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (119,'Elesham of the Paps','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (120,'Erenford','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (121,'Errol of Haystack Hall','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (122,'Estermont of Greenstone','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (123,'Estren of Wyndhall','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (124,'Falwell','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (125,'Farman of Faircastle','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (126,'Farring','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (127,'Farrow','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (128,'Farwynd of Sealskin Point','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (129,'Farwynd of the Lonely Light','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (130,'Fell of Felwood','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (131,'Fenn','North (Crannogmen)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (132,'Ferren','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (133,'Fisher of the Misty Isle','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (134,'Fisher of the Stony Shore','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (135,'Flint of Breakstone Hill','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (136,'Flint of Flint''s Finger','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (137,'Flint of the mountains','North (Mountain Clans)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (138,'Flint of Widow''s Watch','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (139,'Florent of Brightwater Keep','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (140,'Follard','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (141,'Foote','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (142,'Foote of Nightsong','Stormlands (Marcher Lords)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (143,'Footly of Tumbleton','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (144,'Forrester','North (Wolfswood Clans)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (145,'Fossoway of Cider Hall','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (146,'Fossoway of New Barrel','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (147,'Fowler of Skyreach','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (148,'Frey of Riverrun','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (149,'Frey of the Crossing','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (150,'Frost','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (151,'Gardener of Highgarden','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (152,'Gargalen of Salt Shore','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (153,'Garner','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (154,'Gaunt','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (155,'Glover of Deepwood Motte','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (156,'Goodbrook','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (157,'Goodbrother of Corpse Lake','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (158,'Goodbrother of Crow Spike Keep','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (159,'Goodbrother of Downdelving','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (160,'Goodbrother of Orkmont','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (161,'Goodbrother of Shatterstone','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (162,'Goodbrother of Hammerhorn','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (163,'Goode','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (164,'Gower','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (165,'Graceford of Holyhall','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (166,'Grafton of Gulltown','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (167,'Grandison of Grandview','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (168,'Graves','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (169,'Greenfield of Greenfield','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (170,'Greengood','North (Crannogmen)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (171,'Greenhill','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (172,'Greenwood','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (173,'Grell','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (174,'Grey','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (175,'Greyiron of Orkmont','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (176,'Greyjoy of Pyke','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (177,'Greystark of the Wolf''s Den','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (178,'Grimm of Greyshield','Reach (Shield Islands)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (179,'Groves','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (180,'Haigh','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (181,'Hamell','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (182,'Harclay','North (Mountain Clans)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (183,'Hardy','Crownlands (Crackclaw Point)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (184,'Hardyng','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (185,'Harlaw of Grey Garden','Iron Islands (Shield Islands)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (186,'Harlaw of Harlaw Hall','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (187,'Harlaw of Harridan Hill','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (188,'Harlaw of Harlaw','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (189,'Harlaw of the Tower of Glimmering','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (190,'Harroway of Harrenhal','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (191,'Harte','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (192,'Hastwyck','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (193,'Hasty','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (194,'Hawick of Saltpans','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (195,'Hawthorne','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (196,'Hayford of Hayford','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (197,'Heddle','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (198,'Herston','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (199,'Hersy of Newkeep','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (200,'Hetherspoon','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (201,'Hewett of Oakenshield','Reach (Shield Islands)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (202,'Hightower of the Hightower','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (203,'Hoare of Orkmont','Iron Islands (origin)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (204,'Hogg of Sow''s Horn','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (205,'Hollard','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (206,'Holt','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (207,'Holt','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (208,'Hook','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (209,'Hornwood of Hornwood','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (210,'Horpe','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (211,'Hull','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (212,'Humble','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (213,'Hunt','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (214,'Hunter of Longbow Hall','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (215,'Hutcheson','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (216,'Inchfield','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (217,'Ironmaker','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (218,'Ironsmith','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (219,'Jast','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (220,'Jordayne of the Tor','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (221,'Justman','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (222,'Karstark of Karhold','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (223,'Keath','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (224,'Kellington','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (225,'Kenning of Harlaw','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (226,'Kenning of Kayce','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (227,'Kettleblack','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (228,'Kidwell of Ivy Hall','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (229,'Knott','North (Mountain Clans)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (230,'Kyndall','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (231,'Ladybright','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (232,'Lake','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (233,'Lake','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (234,'Langward','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (235,'Lannett','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (236,'Lannister of Casterly Rock','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (237,'Lannister of Darry','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (238,'Lannister of Lannisport','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (239,'Lanny','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (240,'Lantell','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (241,'Leek','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (242,'Lefford of the Golden Tooth','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (243,'Leygood','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (244,'Liddle','North (Mountain Clans)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (245,'Lightfoot','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (246,'Lipps','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (247,'Locke of Oldcastle','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (248,'Lolliston','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (249,'Long','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (250,'Longthorpe of Longsister','Vale of Arryn (Sistermen)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (251,'Longwaters','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (252,'Lonmouth','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (253,'Lorch','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (254,'Lothston of Harrenhal','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (255,'Lowther','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (256,'Lyberr','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (257,'Lychester','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (258,'Lydden of Deep Den','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (259,'Lynderly of Snakewood','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (260,'Magnar of Kingshouse','North (Skagosi Clans)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (261,'Mallery','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (262,'Mallister of Seagard','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (263,'Manderly of White Harbor','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (264,'Mandrake','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (265,'Manning','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (266,'Manwoody of Kingsgrave','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (267,'Marbrand of Ashemark','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (268,'Marsh','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (269,'Martell of Sunspear','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (270,'Massey of Stonedance','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (271,'Meadows of Grassy Vale','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (272,'Melcolm of Old Anchor','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (273,'Merlyn of Pebbleton','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (274,'Merryweather of Longtable','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (275,'Mertyns of Mistwood','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (276,'Middlebury','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (277,'Mollen','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (278,'Moore','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (279,'Mooton of Maidenpool','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (280,'Moreland','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (281,'Mormont of Bear Island','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (282,'Morrigen of Crow''s Nest','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (283,'Moss','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (284,'Mudd of Oldstones','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (285,'Mullendore of Uplands','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (286,'Musgood','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (287,'Myatt','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (288,'Myre of Harlaw','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (289,'Nayland of Hag''s Mire','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (290,'Netley','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (291,'Norcross','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (292,'Norrey','North (Mountain Clans)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (293,'Norridge','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (294,'Nute of Oakenshield','Iron Islands (Shield Islands)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (295,'Nutt','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (296,'Oakheart of Old Oak','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (297,'Oldflowers','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (298,'Orkwood of Orkmont','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (299,'Orme','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (300,'Osgrey of Leafy Lake','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (301,'Osgrey of Standfast','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (302,'Overton','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (303,'Paege','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (304,'Parren','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (305,'Payne','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (306,'Peake of Starpike','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (307,'Peasebury of Poddingfield','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (308,'Peat','North (Crannogmen)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (309,'Peckledon','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (310,'Pemford','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (311,'Penny','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (312,'Penrose of Parchments','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (313,'Perryn','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (314,'Piper of Pinkmaiden','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (315,'Plumm','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (316,'Pommingham','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (317,'Poole','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (318,'Potter','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (319,'Prester of Feastfires','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (320,'Pryor of Pebble','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (321,'Pyle','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (322,'Pyne','Crownlands (Crackclaw Point)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (323,'Qoherys of Harrenhal','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (324,'Qorgyle of Sandstone','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (325,'Quagg','North (Crannogmen)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (326,'Rambton','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (327,'Redbeard','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (328,'Redding','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (329,'Redfort of Redfort','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (330,'Redwyne of the Arbor','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (331,'Reed of Greywater Watch','North (Crannogmen)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (332,'Reyne of Castamere','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (333,'Rhysling','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (334,'Risley of Risley Glade','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (335,'Rogers of Amberly','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (336,'Rollingford','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (337,'Roote of Lord Harroway''s Town','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (338,'Rosby of Rosby','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (339,'Rowan of Goldengrove','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (340,'Roxton of the Ring','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (341,'Royce of Runestone','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (342,'Royce of the Gates of the Moon','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (343,'Ruskyn','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (344,'Ruthermont','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (345,'Ruttiger','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (346,'Ryder of the Rills','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (347,'Ryger of Willow Wood','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (348,'Rykker of Duskendale','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (349,'Ryswell of the Rills','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (350,'Saltcliffe of Saltcliffe','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (351,'Santagar of Spottswood','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (352,'Sarsfield of Sarsfield','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (353,'Sawyer','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (354,'Seaworth of Cape Wrath','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (355,'Selmy of Harvest Hall','Stormlands (Marcher Lords)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (356,'Serrett of Silverhill','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (357,'Serry of Southshield','Reach (Shield Islands)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (358,'Sharp','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (359,'Shawney','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (360,'Shell','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (361,'Shell','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (362,'Shepherd','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (363,'Shermer of Smithyton','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (364,'Shett of Gull Tower','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (365,'Shett of Gulltown','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (366,'Slate of Blackpool','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (367,'Sloane','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (368,'Slynt of Harrenhal','Crownlands (origin)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (369,'Smallwood of Acorn Hall','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (370,'Sparr of Great Wyk','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (371,'Spicer of Castamere','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (372,'Stackhouse','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (373,'Stackspear','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (374,'Staedmon of Broad Arch','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (375,'Stane of Driftwood Hall','North (Skagosi Clans)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (376,'Stark of Winterfell','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (377,'Staunton of Rook''s Rest','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (378,'Stokeworth of Stokeworth','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (379,'Stonehouse of Old Wyk','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (380,'Stonetree of Harlaw','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (381,'Stout of Goldgrass','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (382,'Strickland','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (383,'Strong of Harrenhal','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (384,'Suggs','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (385,'Sunderland of the Three Sisters','Vale of Arryn (Sistermen)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (386,'Sunderly of Saltcliffe','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (387,'Sunglass of Sweetport Sound','Crownlands (Dragonstone)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (388,'Swann of Stonehelm','Stormlands (Marcher Lords)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (389,'Swyft of Cornfield','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (390,'Swygert','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (391,'Tallhart of Torrhen''s Square','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (392,'Tarbeck of Tarbeck Hall','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (393,'Targaryen of King''s Landing','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (394,'Tarly of Horn Hill','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (395,'Tarth of Evenfall Hall','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (396,'Tawney of Orkmont','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (397,'Teague','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (398,'Templeton of Ninestars','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (399,'Terrick','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (400,'Thenn','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (401,'Thorne','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (402,'Toland of Ghost Hill','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (403,'Tollett of the Grey Glen','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (404,'Torrent of Littlesister','Vale of Arryn (Sistermen)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (405,'Towers','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (406,'Towers of Harrenhal','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (407,'Toyne','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (408,'Trant of Gallowsgrey','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (409,'Tudbury','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (410,'Tully of Riverrun','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (411,'Turnberry','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (412,'Tyrell of Brightwater Keep','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (413,'Tyrell of Highgarden','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (414,'Uffering','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (415,'Uller of the Hellholt','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (416,'Umber of the Last Hearth','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (417,'Upcliff of the Witch Isle','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (418,'Vaith of the Red Dunes','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (419,'Vance of Atranta','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (420,'Vance of Wayfarer''s Rest','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (421,'Varner','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (422,'Velaryon of Driftmark','Crownlands (Dragonstone)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (423,'Vikary','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (424,'Volmark of Volmark','Iron Islands (Shield Islands)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (425,'Vypren','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (426,'Vyrwel of Darkdell','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (427,'Wade','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (428,'Wagstaff','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (429,'Warrick','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (430,'Waterman','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (431,'Waxley of Wickenden','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (432,'Wayn','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (433,'Waynwood of Ironoaks','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (434,'Weatherwax','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (435,'Weaver','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (436,'Webber of Coldmoat','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (437,'Wells','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (438,'Wells','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (439,'Wendwater','Crownlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (440,'Wensington','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (441,'Westbrook','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (442,'Westerling of the Crag','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (443,'Whitfield','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (444,'Whent of Harrenhal','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (445,'Whitehead of the Weeping Town','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (446,'Whitehill of Highpoint','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (447,'Willum','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (448,'Wode','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (449,'Woodfoot of Bear Island','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (450,'Woodhull','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (451,'Woods','North (Wolfswood Clans)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (452,'Woodwright','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (453,'Woolfield','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (454,'Wull','North (Mountain Clans)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (455,'Wydman','Vale of Arryn');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (456,'Wyl of the Boneway','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (457,'Wylde of Rain House','Stormlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (458,'Wynch of Iron Holt','Iron Islands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (459,'Wythers','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (460,'Yarwyck','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (461,'Yelshire','Reach');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (462,'Yew','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (463,'Yronwood of Yronwood','Dorne');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (464,'Branfield','Unknown');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (465,'Forrester of Ironrath','North (Wolfswood Clans)');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (466,'Glenmore of Rillwater Crossing','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (467,'Tuttle','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (468,'Whitehill','North');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (469,'Harlton of Castlewood','Riverlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (470,'Sarwyck of Riverspring','Westerlands');
INSERT INTO casas(id_casas,nome_casas,Regiao) VALUES (471,'Westford','Westerlands');